# Generated by Django 3.2.7 on 2021-09-19 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='이름')),
                ('latex', models.CharField(max_length=100, verbose_name='LaTex')),
            ],
            options={
                'verbose_name': '타일',
                'verbose_name_plural': '타일들',
            },
        ),
        migrations.CreateModel(
            name='TileSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_allocated', models.BooleanField(verbose_name='배치 여부')),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='team.team')),
                ('tile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='game.tile')),
            ],
            options={
                'verbose_name': '슬롯',
                'verbose_name_plural': '슬롯들',
                'ordering': ['order'],
            },
        ),
    ]
