# Generated by Django 3.2.7 on 2021-09-19 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, verbose_name='이름')),
                ('score', models.BigIntegerField(verbose_name='점수')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀들',
            },
        ),
    ]
